export declare const START_OF_NEW_MONTH_IDX = 7;
export declare const ONE_YEAR = 1;
export declare const ONE_MONTH = 1;
export declare const MONDAY_ORDINAL_NUMBER = 1;
export declare const ONE_WEEK = 7;
export declare const DECEMBER_ORDINAL_NUMBER = 11;
export declare const JANUARY_ORDINAL_NUMBER = 0;
export declare const MONTHS_IDX_LIST: number[];
export declare const DAYS_IDX_LIST: number[];
export declare const MAX_DATES_LENGTH = 42;
export declare const ONE_DECADE = 10;
