name: Quality Assurance

on: pull_request

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install npm dependencies
        run: npm ci --prefer-offline --cache=./.npm

      - name: Run prettier check
        run: npx prettier --check .
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install npm dependencies
        run: npm ci --prefer-offline --cache=./.npm

      - name: Run eslint check
        run: npx eslint . --max-warnings 0
